### PR TITLE
made compile in linux; register commands test

### LINKED ISSUE #59: Fix compile errors under Linux
When MCUX is used under Linux this repos does not compile. Reason are several 'typos' mainly within include directives asking for .h files with wrong capitalized letters in it!

### PR DESCRIPTION
**Pull request by kodsurf**
fix #59

### CODE REVIEW

File: HardwareTests/src/mod/cli/cli.c [hunk 1]
```diff
@@ -60,6 +60,7 @@ int cmdsProcessed = 0;
 // ----------------------
 void processLine();
 void CliShowStatistics(int argc, char *argv[]);
+void MyOwnFunction(void);
```
Comment (RobertK66) [inline HardwareTests/src/mod/cli/cli.c]: You did it right here but this should go to Your module (The LED module in this case).

File: HardwareTests/src/mod/cli/cli.c [hunk 2]
```diff
@@ -178,33 +179,50 @@ void RegisterCommand(char* cmdStr, void (*callback)(int argc, char *argv[])) {
 	}
 }
 
+
+void MyOwnFunction(void){
+	printf("Hiiiii my new command");
+	//Chip_GPIO_SetPinOutLow(LPC_GPIO, 0, 22); //turn blue on
+	Chip_GPIO_SetPinToggle(LPC_GPIO, 0, 22);
+}
+
```
Comment (RobertK66) [inline HardwareTests/src/mod/cli/cli.c:183]: The holw function should be in ...LED.c

File: HardwareTests/src/mod/cli/cli.c [hunk 3]
```diff
@@ -178,33 +179,50 @@ void RegisterCommand(char* cmdStr, void (*callback)(int argc, char *argv[])) {
...
 // This module init from main module. Remark: The Uart initialization is done in CliInitUart() called by board init.
 void CliInit() {
 	RegisterCommand("cliStat", CliShowStatistics);
+	RegisterCommand("testCMD", MyOwnFunction); //you register commands here
```
Comment (RobertK66) [inline HardwareTests/src/mod/cli/cli.c]: And this line goes to your LEDInit()

File: HardwareTests/src/mod/cli/cli.c [hunk 4]
```diff
@@ -178,33 +179,50 @@ void RegisterCommand(char* cmdStr, void (*callback)(int argc, char *argv[])) {
...
 	printf(CLI_PROMPT);
 }
 
+
+
 // This is module main loop entry. Do not use (too much) time here!!!
 void CliMain(){
 	int ch;
 
+	char *myStr = "Hello";
```
Comment (RobertK66) [inline HardwareTests/src/mod/cli/cli.c]: I think this is debug rest !? or . If so pls. remove....

File: HardwareTests/src/mod/cli/cli.c [hunk 5]
```diff
@@ -178,33 +179,50 @@ void RegisterCommand(char* cmdStr, void (*callback)(int argc, char *argv[])) {
...
 
-		if ((cliRxPtrIdx >= CLI_RXBUFFER_SIZE) ||
+		if ((cliRxIdx >= CLI_RXBUFFER_SIZE) ||
 			 ch == 0x0a ||
 			 ch == 0x0d) 	{
-			cliRxBuffer[cliRxPtrIdx] = 0x00;
+			cliRxBuffer[cliRxIdx] = 0x00;
+			printf("PRINT RECEIVED CMD\n");
+			printf (cliRxBuffer);
+			printf("\n  GOING to process line \n");
```
Comment (RobertK66) [inline HardwareTests/src/mod/cli/cli.c]: Pls. rtemove your debuging stuff here

File: HardwareTests/src/mod/thr/thruster.c [hunk 6]
```diff
@@ -11,8 +11,9 @@
 
 // ... include dependencies on other modules if needed ....
 // #include "..\..\globals.h"   // use if needed
-#include "..\..\layer1\UART\uart.h"
-#include "..\cli\cli.h"
+//#include "..\..\layer1\UART\uart.h"
+#include "/home/jevgeni/climb_base/Climb-Obc-Hardwaretest/HardwareTests/src/layer1/UART/uart.h"
```
Comment (RobertK66) [inline HardwareTests/src/mod/thr/thruster.c]: You forgot this? or why can't this be done relative here

**Review by RobertK66 — CHANGES_REQUESTED** [review]
`Great stuff but pls. resolve comments...

**Comment by RobertK66** [comment]
Ok, in future i will make the real merge with my login :-).
